workflows:
  ios-release:
    name: iOS App Store Build
    working_directory: pinspace_app  # Runs scripts from your project subdirectory
    max_build_duration: 120
    integrations:
      app_store_connect: PinSpace App Stpre Connect Key  # Match your API key name in Codemagic UI > Teams > Integrations
    environment:
      vars:
        APP_STORE_APPLE_ID: "6748885422"  # Your app's Apple ID from App Store Connect
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.PinSpace
    scripts:
      - flutter pub get
      - cd ios && pod install
      - xcode-project use-profiles
      - flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration  # Uses your UI-configured API key
        submit_to_app_store: true  # Or submit_to_testflight: true for testing