workflows:
  ios-release:
    name: iOS App Store Build
    working_directory: pinspace_app  # Add this line
    max_build_duration: 120
    integrations:
      app_store_connect: default  # This must match the name you gave your API key in the Codemagic UI
    environment:
      vars:
        APP_STORE_APPLE_ID: "6748885422"  # Your app's Apple ID
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.PinSpace
    scripts:
      - flutter pub get
      - cd ios && pod install
      - xcode-project use-profiles
      - name: Increment build number
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
      - flutter build ipa --release --build-number=$BUILD_NUMBER --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration  # This fixes the authentication error by using your UI-configured API key
        submit_to_app_store: true  # Set to true for App Store submission; use submit_to_testflight: true for TestFlight